routes:
  /:
    controller: channel
    data:
      post: page.home
    template: page

collections:
  /blog/:
    permalink: /blog/{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
