routes:
  #/:
  #  controller: channel
  #  data:
  #    post: page.home
  #  template: home

collections:
  #/blog/:
  /:
    #permalink: /blog/{slug}/
    permalink: /{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
